[build]
  publish = "hugo_site/public"
  command = "cd hugo_site && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.121.1"
  NODE_VERSION = "18"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_ENV = "development"

# Force Hugo detection - ignore Python files
[build.ignore]
  command = "exit 0"

# Override build detection
[build.processing]
  skip_processing = false

# Headers for sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle Hugo's pretty URLs
[[redirects]]
  from = "/posts"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/categories"
  to = "/categories/"
  status = 301

[[redirects]]
  from = "/tags"
  to = "/tags/"
  status = 301

# Sitemap redirect
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-clean.xml"
  status = 200

# Default 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
