[build]
  publish = "hugo_site/public"
  command = "cd hugo_site && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.121.1"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_ENV = "development"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Basic redirects
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
