[build]
  publish = "hugo_site/public"
  command = "cd hugo_site && hugo --minify"

[build.environment]
  HUGO_VERSION = "0.121.1"

[context.production.environment]
  HUGO_ENV = "production"

# Headers for sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

# Handle Hugo's pretty URLs
[[redirects]]
  from = "/posts"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/categories"
  to = "/categories/"
  status = 301

[[redirects]]
  from = "/tags"
  to = "/tags/"
  status = 301

# Handle trailing slashes for all pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Default 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
